[package]
name = "sake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
serde = "1.0.152"
bincode = "1.3.3"
byteorder = "1.4.3"
tokio = { version = "1.25.0", features = ["full"] }
